service: nest-mono
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: ca-central-1
  memorySize: 1024
  timeout: 15
  environment:
    NODE_OPTIONS: '--enable-source-maps'
    # Pull SecureString from SSM Parameter Store
    MONGODB_URI: ${ssm:/nest-mono/MONGODB_URI~true}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'   # API Gateway HTTP API v2, proxy all routes

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true
    platform: node
    target: node20
    sourcemap: true
    # Keep externals empty unless you need native deps
    external: []
