name: Deploy to AWS Lambda (Serverless v3)

on:
  push:
    branches: [ master ]   # change to main if needed
  workflow_dispatch:

env:
  AWS_REGION: ca-central-1
  STAGE: prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # Avoid overlapping deploys on the same branch
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials (keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy with Serverless v3
        run: npx serverless@3 deploy --stage $STAGE --region $AWS_REGION

      - name: Show stack outputs
        run: npx serverless@3 info --stage $STAGE --region $AWS_REGION